name: publish-build
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew chiseledBuild

      - name: prepare release jars
        run: |
          mkdir release
          
          for dir in versions/*; do
            mc=$(basename "$dir")
          
            for jar in "$dir"/build/libs/*.jar; do
              name=$(basename "$jar" .jar)
          
              if [[ "$name" == *-sources ]]; then
                base="${name%-sources}"
                cp "$jar" "release/${base}+mc${mc}-sources.jar"
              else
                cp "$jar" "release/${name}+mc${mc}.jar"
              fi
            done
          done

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: release/*.jar

      - name: upload jars to release
        run: gh release upload "${{ github.event.release.tag_name }}" release/*.jar
        env:
          GH_TOKEN: ${{ github.token }}